name: Health Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    if: secrets.BACKEND_URL != ''
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
    steps:
      - name: Health check
        run: curl -fsS --max-time 10 "$BACKEND_URL/health"
